version: 2

sources:
  - name: cds
    schema:  "{{ var('cds_schema') | trim }}"
    tables:
      - name: d_business_unit
      - name: d_third_link
      - name: d_currency
      - name: mtf_exchange_rate
      - name: sites_attribut_0plant_branches
      - name: sales_organizations_texts
      - name: supply_plant
      - name: d_sku_h
      - name: d_hierarchy_supply
      - name: d_general_data_store
      - name: d_sales_data_material
      - name: f_delivery_detail
      - name: f_transaction_detail
      - name: f_transaction_sustainable
      - name: new_a_product_impact
      - name: f_stock_pictures_value
      - name: d_day
  - name: ods
    schema: "{{ var('ods_schema') | trim }}"
    tables:
      - name: opv_review__review
      - name: opv_catalog__product
  - name: silver
    schema: "{{ var('silver_schema') | trim }}"
    tables:
      - name: product_nature
      - name: product_model
      - name: product_conception
      - name: product_type

models:
  - name: int_model